alias rsyncssh='rsync -e ssh -v --progress'

gea() { vim "$@" && git a "$@"; }

pd-sync() { git ci -m "Sync $1" "$1"; }

pd-mod-upgrade() { local a="$1"; local b="$2"; git ci -m "Upgrade $a -> $b" "$a" "$b"; }

pd-add-file() { git a "$1" && git ci -m "Add $1" "$1"; }

pd-add-dir() { git a "$1" && git ci -m "Add $1/" "$1"; }

pd-config-ignore() { local gi=config/.gitignore; echo "${1##config}" >> $gi; sort < $gi > $gi.new && mv -f $gi.new $gi; } 

##
# vim: ts=2 sw=2 et :
##
