alias rsyncssh='rsync -e ssh -v --progress'

sync() { git ci -m "Sync $1" "$1"; }

gea() { vim "$@" && git a "$@"; }

gstgrep() { git st |grep -i "$1"; }

pu() { local a="$1"; local b="$2"; git ci -m "Upgrade $a -> $b" "$a" "$b"; }

paf() { git a "$1" && git ci -m "Add $1" "$1"; }

pad() { git a "$1" && git ci -m "Add $1/" "$1"; }

pcig() { local gi=config/.gitignore; echo "${1##config}" >> $gi; sort < $gi > $gi.new && mv -f $gi.new $gi; } 

##
# vim: ts=2 sw=2 et :
##
