
#General settings
[General]
	#Ignore speed boosts for field of view
	#Range: 100 ~ 10000000
	armorStandMaxPower = 1000000

[Modules]

	[Modules.Energy_Storage]

		[Modules.Energy_Storage.battery_basic]
			#Range: 0.0 ~ 2.147483647E9
			base_maxEnergy = 1000000.0
			isAllowed = true
			#Range: 0.0 ~ 2.147483647E9
			base_maxTransfer = 1000000.0

		[Modules.Energy_Storage.battery_advanced]
			#Range: 0.0 ~ 2.147483647E9
			base_maxEnergy = 1.0E7
			isAllowed = true
			#Range: 0.0 ~ 2.147483647E9
			base_maxTransfer = 1.0E7

		[Modules.Energy_Storage.battery_elite]
			#Range: 0.0 ~ 2.147483647E9
			base_maxEnergy = 1.0E8
			isAllowed = true
			#Range: 0.0 ~ 2.147483647E9
			base_maxTransfer = 1.0E8

		[Modules.Energy_Storage.battery_ultimate]
			#Range: 0.0 ~ 2.147483647E9
			base_maxEnergy = 1.0E9
			isAllowed = true
			#Range: 0.0 ~ 2.147483647E9
			base_maxTransfer = 1.0E9

