!!dev.wuffs.squatgrow.config.SquatGrowConfig
allowAdventureTwerking: true
chance: 0.5
debug: false
enableMysticalCrops: true
ignoreList: ['minecraft:grass_block', 'minecraft:grass', 'minecraft:tall_grass', 'minecraft:netherrack',
  'minecraft:warped_nylium', 'minecraft:crimson_nylium', 'botania:white_mystical_flower',
  'botania:orange_mystical_flower', 'botania:magenta_mystical_flower', 'botania:light_blue_mystical_flower',
  'botania:yellow_mystical_flower', 'botania:lime_mystical_flower', 'botania:pink_mystical_flower',
  'botania:gray_mystical_flower', 'botania:light_gray_mystical_flower', 'botania:cyan_mystical_flower',
  'botania:purple_mystical_flower', 'botania:blue_mystical_flower', 'botania:brown_mystical_flower',
  'botania:green_mystical_flower', 'botania:red_mystical_flower', 'botania:black_mystical_flower']
range: 3
requireHoe: false
useWhitelist: false
